Add google login
iwsh/http-chat pull request #24
Opened 2023-02-23 10:06 UTC by kegoly

Google アカウントを利用して、ログインすることができるように機能追加しました。

2023-02-23 13:12 UTC, iwsh requested changes

2023-02-23 13:12 UTC, iwsh commented on doc/testcase.md
> +- Login with both Github and Google and redirect to /chat/
前回追加してもらったときは気が付きませんでしたが、"redirect to /chat"ですね
それと7行目は2つの確認項目が混じっているように見えます（loginなしで/chatへのアクセス・無効なcodeでログインして401）

2023-02-23 13:12 UTC, iwsh commented on ui/src/components/Login.js
> +        });
ここってログイン先のURLが違うだけですか？共通化できそうな気がします。
```
if (code){
  if (googleの判定){
     path = google用path
  } else {
     path = github用
  }
  ~.post(path, {
...
```

2023-02-23 13:58 UTC, iwsh commented
close #22

2023-02-25 09:29 UTC, kegoly commented
上の3点について、修正した上でプッシュしておいたのでご確認お願いできますでしょうか。

2023-02-25 09:43 UTC, iwsh approved these changes
LGTM

2023-02-25 09:44 UTC, merged