Format UTC with seconds precision
iwsh/http-chat pull request #34
Opened 2023-03-26 06:08 UTC by kegoly

UTCの表示がマイクロ秒まで表示されていたので、小数点以下を切り捨てて秒までを表示するように改修してます。

2023-03-26 16:10 UTC, iwsh requested changes

2023-03-26 16:10 UTC, iwsh commented on ui/src/pages/Chat.js
> +    const jstdate = new Date(Date.parse(strDate));
utcのcaseでも使っているので変数名を `jstdata` から変更してください

2023-03-26 16:10 UTC, iwsh commented on ui/src/pages/Chat.js
> +          [
一旦このままでも良いですが、日付文字列の生成をDateの関数等でもっと簡潔に書けると嬉しいです

2023-03-28 10:06 UTC, kegoly commented on ui/src/pages/Chat.js
> +          [
承知しました。

2023-03-28 10:07 UTC, kegoly commented on ui/src/pages/Chat.js
> +    const jstdate = new Date(Date.parse(strDate));
`date`に変数名を修正しました。

2023-03-28 16:18 UTC, iwsh approved these changes

2023-03-31 16:05 UTC, merged